### ISSUE TITLE
Feature request: Add Receive tab with QR code support

### ISSUE THREAD

**Issue by rex4539** [ZECmate/ZECmate-swing-wallet#10]
See https://github.com/adityapk00/zec-qt-wallet for reference.

**Comment by Cabecinha84** [comment]
QR code was added to own address page on version 6.1.0. Right click on the address you want to get the qr code and select "Generate QR Code"

**Comment by Cabecinha84** [comment]
Sorry, it was added to zelcash swing wallet version 6.1.0. But will be merged to ZecMate.

**Comment by TheTrunk** [comment]
6030a14bb7580e2923da5251b33a56c6db24a019
