### ISSUE TITLE
Error when trying to obtain Sapling private key

### ISSUE THREAD

**Issue by rex4539** [ZECmate/ZECmate-swing-wallet#9]
Reproducibility: always

Steps:
Own Addresses -> Right click on a Sapling address -> Obtain private key

What happened:
![screen shot 2018-10-29 at 06 56 36](https://user-images.githubusercontent.com/227442/47630204-2930ea80-db48-11e8-8c02-8c61dda6a002.png)

Expected result:
Private key is displayed.

**Comment by sandakersmann** [comment]
I have the same issue.
